---
title: "Stemmatology workshop"
author: "JB Camps"
date: "2026-03-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# if necessary:
# install.packages("stemmatology")
library("stemmatology")
library("ggplot2")
source("functions_new.R")
```


# Textual criticism-based "PCC" method

For the documentation:

```{r}
?`stemmatology-package`
```


```{r}
# Import data
data = import.TEIApparatus_corr(file = "data/cliges_unified_fixed_unique.xml", appTypes = c("lexsem:weak", "lexsem:strong", "lexsem:nonsense", "absence", "order"))
# Check which witnesses have sufficient readings, and keep them
apply(X = is.na(data), MARGIN = 2, FUN = sum) / nrow(data)
data = data[, c("A", "B", "C", "P", "R", "S")]
```


```{r}
# Explore and analyse
select = PCC.Exploratory(data, omissionsAsReadings = FALSE, threshold = 0.1, ask = FALSE, pauseAtPlot = FALSE) #Threshold 0.10

stemma = PCC.Stemma(select$database, verbose = TRUE, ask = FALSE)
```


# Cladistics

```{r}
library("phangorn")
data = phyDat(as.matrix(t(data)), type = "USER", levels = 0:10, ambiguity=NA)
```

## Neighbour-joining

Neighbour joining,
```{r}
dm <- dist.ml(data)
tree <- NJ(dm)
plot(tree, "unrooted")
```
```{r}
tree <- UNJ(dm)
plot(tree, "unrooted")
```

## Maximum parsimony

```{r}
mm_start <- random.addition(data)
# Applying the pratchet method for maximum parsimony
# Default, fitch + SPR
mm_tree <- pratchet(data, start = mm_start, minit = 1000, maxit = 10000, all = TRUE, trace = 0, method = "fitch", rearrangements = "SPR", perturbation = "ratchet") # "The "fitch" algorithm only works correct for binary trees"
# Alternative
#mm_tree <- pratchet(data, start = mm_start, minit = 1000, maxit = 10000, all = TRUE, trace = 0, method = "sankoff", rearrangements = "SPR", perturbation = "ratchet")
```

```{r}
mm_tree
```

```{r}
parsimony(mm_tree, data)
```

```{r}
# Determining branch length
mm_tree <- acctran(mm_tree, data)
# Eliminating too short branches, to integrate polytomies/multifurcations
# we prune away internal edges of length tol (default = 1e-08), so our trees may contain multifurcations.
mm_tree  <- di2multi(mm_tree)
```

```{r}
# In case of several competing trees
#plot(consensus(mm_tree), "unrooted", main="Unrooted consensus tree")
plotBS(mm_tree, type = "unrooted")
plot(mm_tree, "unrooted", main="Unrooted tree")
```

## Maximum likelihood

```{r}
# test different models
mt <- modelTest(data, model=c("JC", "F81", "K80", "HKY", "SYM", "GTR"), control = pml.control(trace = 0))
mt
```

```{r}
fit_mt <- pml_bb(mt, control = pml.control(trace = 0))
#fitGTR <- pml_bb(data, model="GTR")
```

And now bootstrapping,

```{r}
bs <- bootstrap.pml(fit_mt, bs=100, optNni=TRUE, control = pml.control(trace = 0))
```

```{r}
plotBS(midpoint(fit_mt$tree), p = .5, type="p", digits=2, main="Ultrafast bootstrap")
plotBS(midpoint(fit_mt$tree), bs, p = 50, type="p", main="Standard bootstrap")
#plotBS(midpoint(fit_mt$tree), bs, p = 50, type="p", digits=0, method = "TBE", main="Transfer bootstrap")
```




